### ISSUE TITLE
[bug]: while clicking on image modal controller is not getting open, nor it is giving any error.

### ISSUE THREAD

**Issue by priyankataneja** [SimonGolms/ngx-ionic-image-viewer#54] opened 2021-03-14 17:25 UTC
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:**

```
insert the output from ionic info here
```

**Comment by priyankataneja** [comment] 2021-03-14 17:28
**.html**
 <img [src]="transform(image.photo)" (click)="openViewer()"/>

**.ts**
async openViewer() {
    const modal = await this.modalController.create({
      component: ViewerModalComponent,
      componentProps: {
        src: this.imgUrl, // required
        title: 'Silhoutte (Programmatic)', // optional
        text: 'Photo by Mayur Gala on Unsplash', // optional
      },
      cssClass: 'ion-img-viewer', // required
      keyboardClose: true,
      showBackdrop: true,
    });

    return await modal.present();
  }


its not presenting  modal
Angulay version ->11.1.2
ionic version->5.5.0

**Comment by SimonGolms** [comment] 2021-03-16 21:25
Hi @priyankataneja, thanks for reporting. I just tried it with the latest version of ionic `ionic start demo blank --type=angular` and cannot reproduce your reported bug. Maybe check the installed versions and if `openViewer` works?!
Unfortunately, since the template and formatting has not really been followed and the bug is not reproducible, I am closing this issue again.
But please feel free to create a new issue by following the template & formatting and provide a reproducible version either as git repo or via https://codesandbox.io/ or https://stackblitz.com/

**Closed by SimonGolms** 2021-03-16 21:25 UTC
